[tool.poetry]
name = "neuralnetwork"
version = "0.1.0"
description = ""
authors = ["malady <sergslutu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
pandas = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
